FROM python:3.9-alpine AS build

WORKDIR /app
RUN pip3 install Flask --prefix ./ 
RUN mv lib/python3.9/site-packages/* ./ && rm -rf pip* setuptools* pkg_resources *distutils* bin lib
COPY ./index.py .
COPY ./templates .

FROM gcr.io/distroless/python3@sha256:db34936540e7bc575cc24a318e41eae7ad8c426b8d8e20a465f0dd67843590eb

COPY --from=build /app/ ./

CMD ["index.py"]
