apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-app
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - image: ghcr.io/2023-4400-exp/4415-python-app:4c985a88573f1af6935ad8d9bacb7337357c4565
          name: python-app
          volumeMounts:
            - mountPath: /var/python-app
              name: python-app-data
      volumes:
        - name: python-app-data
          persistentVolumeClaim:
            claimName: python-app-data
